import {
  AUTH_ERRORS,
  PERMISSION_ERRORS,
  RESOURCE_ERRORS,
  SYSTEM_ERRORS,
  VALIDATION_ERRORS,
} from "../config/messages";

export const ErrorMessages = {
  // Auth
  UNAUTHENTICATED: AUTH_ERRORS.UNAUTHENTICATED,
  UNAUTHENTICATED_EN: AUTH_ERRORS.UNAUTHENTICATED_EN,
  ADMIN_REQUIRED: AUTH_ERRORS.ADMIN_REQUIRED,

  // Validation
  INVALID_ARGUMENT: VALIDATION_ERRORS.INVALID_ARGUMENT,
  MISSING_REQUIRED: VALIDATION_ERRORS.MISSING_REQUIRED,
  IMAGE_BASE64_REQUIRED: VALIDATION_ERRORS.IMAGE_BASE64_REQUIRED,
  SELF_ACTION_NOT_ALLOWED: (action: string) => `You cannot ${action} yourself.`,

  // Permission
  CIRCLE_DELETE_OWNER_ONLY: PERMISSION_ERRORS.CIRCLE_DELETE_OWNER_ONLY,

  // Resources
  USER_NOT_FOUND: RESOURCE_ERRORS.USER_NOT_FOUND,
  POST_NOT_FOUND: RESOURCE_ERRORS.POST_NOT_FOUND,
  CIRCLE_NOT_FOUND: RESOURCE_ERRORS.CIRCLE_NOT_FOUND,
  TASK_NOT_FOUND: RESOURCE_ERRORS.TASK_NOT_FOUND,

  // Duplicates
  ALREADY_EXISTS: (item: string) => `Already ${item}.`,
  ALREADY_REPORTED: VALIDATION_ERRORS.ALREADY_REPORTED,
  ALREADY_FOLLOWING: "Already following.",

  // System
  INTERNAL_ERROR: SYSTEM_ERRORS.INTERNAL,
} as const;
