import '../../shared/models/name_part_model.dart';

/// 名前パーツ（登録時に使う共通パーツ）
/// ここを単一の参照元として、他画面の初期表示に使う。
class NamePartsCatalog {
  static final List<NamePartModel> commonPrefixes = List.unmodifiable([
    NamePartModel(
      id: 'prefix_pre_01',
      text: 'がんばる',
      category: 'positive',
      rarity: 'common',
      type: 'prefix',
      order: 1,
      unlocked: true,
    ),
    NamePartModel(
      id: 'prefix_pre_02',
      text: 'キラキラ',
      category: 'positive',
      rarity: 'common',
      type: 'prefix',
      order: 2,
      unlocked: true,
    ),
    NamePartModel(
      id: 'prefix_pre_03',
      text: '全力',
      category: 'positive',
      rarity: 'common',
      type: 'prefix',
      order: 3,
      unlocked: true,
    ),
    NamePartModel(
      id: 'prefix_pre_04',
      text: '輝く',
      category: 'positive',
      rarity: 'common',
      type: 'prefix',
      order: 4,
      unlocked: true,
    ),
    NamePartModel(
      id: 'prefix_pre_05',
      text: '前向き',
      category: 'positive',
      rarity: 'common',
      type: 'prefix',
      order: 5,
      unlocked: true,
    ),
    NamePartModel(
      id: 'prefix_pre_06',
      text: 'のんびり',
      category: 'relaxed',
      rarity: 'common',
      type: 'prefix',
      order: 6,
      unlocked: true,
    ),
    NamePartModel(
      id: 'prefix_pre_07',
      text: 'まったり',
      category: 'relaxed',
      rarity: 'common',
      type: 'prefix',
      order: 7,
      unlocked: true,
    ),
    NamePartModel(
      id: 'prefix_pre_08',
      text: 'ゆるふわ',
      category: 'relaxed',
      rarity: 'common',
      type: 'prefix',
      order: 8,
      unlocked: true,
    ),
    NamePartModel(
      id: 'prefix_pre_11',
      text: 'コツコツ',
      category: 'effort',
      rarity: 'common',
      type: 'prefix',
      order: 11,
      unlocked: true,
    ),
    NamePartModel(
      id: 'prefix_pre_12',
      text: 'もくもく',
      category: 'effort',
      rarity: 'common',
      type: 'prefix',
      order: 12,
      unlocked: true,
    ),
  ]);

  static final List<NamePartModel> commonSuffixes = List.unmodifiable([
    NamePartModel(
      id: 'suffix_suf_01',
      text: '🐰うさぎ',
      category: 'animal',
      rarity: 'common',
      type: 'suffix',
      order: 1,
      unlocked: true,
    ),
    NamePartModel(
      id: 'suffix_suf_02',
      text: '🐱ねこ',
      category: 'animal',
      rarity: 'common',
      type: 'suffix',
      order: 2,
      unlocked: true,
    ),
    NamePartModel(
      id: 'suffix_suf_03',
      text: '🐶いぬ',
      category: 'animal',
      rarity: 'common',
      type: 'suffix',
      order: 3,
      unlocked: true,
    ),
    NamePartModel(
      id: 'suffix_suf_04',
      text: '🐼パンダ',
      category: 'animal',
      rarity: 'common',
      type: 'suffix',
      order: 4,
      unlocked: true,
    ),
    NamePartModel(
      id: 'suffix_suf_05',
      text: '🐻くま',
      category: 'animal',
      rarity: 'common',
      type: 'suffix',
      order: 5,
      unlocked: true,
    ),
    NamePartModel(
      id: 'suffix_suf_07',
      text: '🌸さくら',
      category: 'nature',
      rarity: 'common',
      type: 'suffix',
      order: 7,
      unlocked: true,
    ),
    NamePartModel(
      id: 'suffix_suf_08',
      text: '🌻ひまわり',
      category: 'nature',
      rarity: 'common',
      type: 'suffix',
      order: 8,
      unlocked: true,
    ),
    NamePartModel(
      id: 'suffix_suf_09',
      text: '⭐ほし',
      category: 'nature',
      rarity: 'common',
      type: 'suffix',
      order: 9,
      unlocked: true,
    ),
    NamePartModel(
      id: 'suffix_suf_12',
      text: '🍙おにぎり',
      category: 'food',
      rarity: 'common',
      type: 'suffix',
      order: 12,
      unlocked: true,
    ),
    NamePartModel(
      id: 'suffix_suf_14',
      text: '🍮プリン',
      category: 'food',
      rarity: 'common',
      type: 'suffix',
      order: 14,
      unlocked: true,
    ),
  ]);
}
